name: deploy docs 
on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - test-ci
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocstrings[python] mkdocs-badges
      - run: |
           # remove badges 
           cat README.md |sed  '/img\.shields\.io/d' > ./data-processing-lib/doc/index.md 
           cp doc/* ./data-processing-lib/doc/
           cp -rf transforms  ./data-processing-lib/doc/transforms
           cp -rf tools ./data-processing-lib/doc/tools
           cd data-processing-lib && mkdocs gh-deploy --force
