
name: Test CI
# for testing purposes
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test data-processing-lib
      run: |
         make -C data-processing-lib DOCKER=docker venv test
    - name: Test Code Transforms
      run: |
         make -C transforms/code DOCKER=docker venv test-src 
    - name: Test Universal Transforms
      run: |
         make -C transforms/universal DOCKER=docker venv test-src 
